In [1]:
from injector_surrogate_quads import SurrogateNN
import numpy as np

In [2]:
nn = SurrogateNN()

In [6]:
variables  = [[ 3.9221e+02,  3.5380e+00,  2.5000e-01,  4.4720e-01, -8.2369e-04,
         1.3596e-02,  5.8000e+01,  2.7935e+00,  7.0000e+01, -9.8690e+00,
        -2.3205e+00,  2.6090e+00, -2.5998e+00, -7.7558e-01,  4.0487e+00,
        -2.5267e+00]]

In [7]:
model = nn.create_torch_model()
nn.create_torch_module(model)

TorchModule(
  (base_model): Sequential(
    (0): Linear(in_features=16, out_features=100, bias=True)
    (1): ELU(alpha=1.0)
    (2): Linear(in_features=100, out_features=200, bias=True)
    (3): ELU(alpha=1.0)
    (4): Dropout(p=0.05, inplace=False)
    (5): Linear(in_features=200, out_features=200, bias=True)
    (6): ELU(alpha=1.0)
    (7): Dropout(p=0.05, inplace=False)
    (8): Linear(in_features=200, out_features=300, bias=True)
    (9): ELU(alpha=1.0)
    (10): Dropout(p=0.05, inplace=False)
    (11): Linear(in_features=300, out_features=300, bias=True)
    (12): ELU(alpha=1.0)
    (13): Dropout(p=0.05, inplace=False)
    (14): Linear(in_features=300, out_features=200, bias=True)
    (15): ELU(alpha=1.0)
    (16): Dropout(p=0.05, inplace=False)
    (17): Linear(in_features=200, out_features=100, bias=True)
    (18): ELU(alpha=1.0)
    (19): Dropout(p=0.05, inplace=False)
    (20): Linear(in_features=100, out_features=100, bias=True)
    (21): ELU(alpha=1.0)
    (22): Linear(in_

In [8]:
nn.pred_sim_units(variables)

tensor([1.7819e+02, 1.4450e+03, 5.4184e-04, 1.4161e-06, 1.1945e-06],
       dtype=torch.float64)

In [9]:
    _variables = {
        'CAMR:IN20:186:R_DIST': 0.424,
        'Pulse_length': 3.061,
        'FBCK:BCI0:1:CHRG_S': 250.00,
        'SOLN:IN20:121:BACT': 0.246,
        'QUAD:IN20:121:BACT': 0.001,
        'QUAD:IN20:122:BACT':  0.0003,
        'ACCL:IN20:300:L0A_ADES': 58000000.0,
        'ACCL:IN20:300:L0A_PDES': -9.54,
        'ACCL:IN20:400:L0B_ADES': 70000000.0,
        'ACCL:IN20:400:L0B_PDES': 9.85,
        'QUAD:IN20:361:BACT': 1.85,
        'QUAD:IN20:371:BACT': -1.85,
        'QUAD:IN20:425:BACT': 1.00,
        'QUAD:IN20:441:BACT': 0.17,
        'QUAD:IN20:511:BACT': -2.64,
        'QUAD:IN20:525:BACT': 2.98,
    }

In [14]:
import torch

In [20]:
torch.set_printoptions(precision=2)

In [15]:
a = list(_variables.values())
x = torch.as_tensor(np.array([a]).astype('float'))
x

tensor([[ 4.2400e-01,  3.0610e+00,  2.5000e+02,  2.4600e-01,  1.0000e-03,
          3.0000e-04,  5.8000e+07, -9.5400e+00,  7.0000e+07,  9.8500e+00,
          1.8500e+00, -1.8500e+00,  1.0000e+00,  1.7000e-01, -2.6400e+00,
          2.9800e+00]])

In [21]:
print(nn.input_pv_to_sim.untransform(x))

tensor([[ 4.24e+02,  1.86e+00,  2.50e-01,  4.78e-01, -2.10e-03, -6.30e-04,
          5.80e+01, -9.54e+00,  7.00e+01,  9.85e+00, -2.00e+00,  2.00e+00,
         -1.08e+00, -1.84e-01,  2.85e+00, -3.22e+00]])


In [24]:
print(nn.input_pv_to_sim.untransform(x)[0][1])

tensor(1.86)


In [25]:
x_in=[ 4.2400e-01,  3.0690e+00,  2.5000e+02,  2.4582e-01,  1.0000e-03,
          3.0000e-04,  5.8000e+07, -9.5400e+00,  7.0000e+07,  9.8500e+00,
          1.8519e+00, -1.8519e+00,  9.2593e-01,  1.6667e-01, -2.6389e+00,
          2.9815e+00]


In [27]:
o = nn.pred_sim_units(x_in)

In [33]:
o

tensor([1.40e+16, 8.87e+16, 6.33e+09, 3.12e+07, 9.23e+07], dtype=torch.float64)

In [32]:
o[1].detach().item()


8.873641829697886e+16